### ISSUE TITLE
Configure MicroCloud with a preseed.yaml

### ISSUE THREAD

**Issue by masnax** [canonical/microcloud#120]
We will want to have support for a yaml preseed file passed into `microcloud init --preseed <yaml>` that will take care of all the otherwise interactive configuration.

To facilitate selecting disks without knowing all the information, we want to be smart about filtering on some key details.

```yaml
lookup_subnet: 10.0.0.1/24 # The subnet to lookup servers over mDNS
systems:
 - name: micro01 # The hostnames of the specific machines we want in the cluster
   ovn_uplink_interface: eth1 # If unset, will take the first available if setting up OVN.
ovn:
  ipv4_gateway: 10.0.0.1/24
  ipv4_range: [10.0.0.100,10.0.0.254]
  ipv6_gateway: ...
disks: # Separate config for local and ceph storage.
  local:
    - id: nvme0n1 # Provide just a string to match exactly
      model:
        filter: "INTEL" # Provide a struct with <filter> and <mode>. Mode defaults to "contains" for strings and "exact" for ints.
        mode: "prefix"
      size:
        filter: "10GiB" 
        mode: "greater_than"
  ceph:
    max_disks: 3 # Total maximum number of expected disks. Expects unlimited if not specified. Fails if not at least 3.
    - id: nvme1n1
      type: 
        filter: "nvme"
        mode: "prefix"
      limit: 1 # Limit of matching selections per machine. Defaults to unlimited.
      machines: ["micro01"] # Machines to consider the filter for. Others will be ignored. Defaults to all. 
      wipe: false # Wipe disks found for this entry on each machine. 
    - size: 30GiB
     ...
```

I've been thinking about something sort of like this, where we have 2 entries for `local` and `ceph`. Each takes a slice of objects containing the fields for a struct of a similar form to `lxdAPI.ResourcesStorageDisk`. The fields will accept either a plain string for an exact match, or an object with `filter` and `mode` as options. Additional fields per disk are `machine`, specifying a list of machines the disk criteria should apply to, `limit`, specifying the number of disks per machine to consider, and `wipe`.

**Comment by masnax** [comment]
@stgraber Here's what I've got so far. I approached the filters by effectively having multi-type fields, where they can either be an exact string, or a struct with a filter type.

**Comment by masnax** [comment]
Here's a slightly more concise version for disks:

```yaml
 disks: # Separate config for local and ceph storage.
   local: # Validation will require each machine specified in "systems" to have exactly one entry in the list.
     - machines: ["micro01", "micro02"]
       model:
         value: "INTEL"
         mode: "contains"
       memory:
         value: "10GiB"
         mode: "greater_than"
       type: "nvme"
     - machines: ["micro03"]
       type: "nvme"
   ceph: # This works similar to `local`, except the validation for machines is one or more, instead of exactly one.
     expected_disks: 6 # expected_disks can take a string or a slice of maps.
     # OR
     expected_disks: ["micro01": 2, "micro02": 2, "micro03": 2]
     - machines: ["micro01","micro02","micro03"]
       limits: ["micro01": 1, "micro02": 2, "micro03": 1] # `limits` is an optional field for `ceph` filters that will limit the number of disks found by this filter for each machine.
       type: "nvme"
     - machines: ["micro01","micro02","micro03"]
       type: "sata"
```

**Comment by stgraber** [comment]
```
lookup_subnet: 10.0.0.1/24 # The subnet to lookup servers over mDNS
systems:
 - name: micro01 # The hostnames of the specific machines we want in the cluster
   ovn_uplink_interface: eth1 # If unset, will take the first available if setting up OVN.
 - name: micro02 # The hostnames of the specific machines we want in the cluster
   ovn_uplink_interface: eth1 # If unset, will take the first available if setting up OVN.
 - name: micro03 # The hostnames of the specific machines we want in the cluster
   ovn_uplink_interface: eth1 # If unset, will take the first available if setting up OVN.
 - name: micro04 # The hostnames of the specific machines we want in the cluster
   ovn_uplink_interface: eth1 # If unset, will take the first available if setting up OVN.
   storage: # If unset, uses the global disk definition to identify disks
     local:
       id: nvme5n1
     ceph:
       - id: nvme4n1
       - id: nvme3n1
ovn:
  ipv4_gateway: 10.0.0.1/24
  ipv4_range: 10.0.0.100-10.0.0.254
  ipv6_gateway: ...
  ipv6_range: # If unset, uses EUI64
storage: # Separate config for local and ceph storage.
  local:
    - id: nvme0n1 # Provide just a string to match exactly
  ceph:
    max_disks: 3 # Total maximum number of expected disks. Expects unlimited if not specified. Fails if not at least 3.
    - filter: "size > 10GiB && size < 50GiB && type == 'nvme'"
      filter_min_match: 1
      filter_max_match: 2
      type: partition
      wipe: true
    - filter: "size > 10GiB && size < 50GiB && type == 'hdd' && partitioned == false"
      filter_min_match: 3
      filter_max_match: 8
      type: disk
      wipe: false
```
