### ISSUE TITLE
feat: add option for specifying the network to use for OVN east-west (underlay) traffic

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/microcloud#239]
JIRA ticket liink: https://warthogs.atlassian.net/jira/software/c/projects/LXD/boards/54?assignee=63d9eb6128cddcc70770aff1&selectedIssue=LXD-635

Add the option to specify the underlay network to be used. Right now, we only have the option to provide the details for the uplink, but the network used for the OVN clustering and thus the network over which the geneve tunnels are created is the same network used for the clustering of LXD and Ceph.

Allowing a user to specify interfaces to be used for an underlay network could serve the purpose of having dedicated VLANs for each purpose i.e. one VLAN for LXD clustering, one for Ceph access, one for Ceph replication and one for OVN.

## Interactive mode

After the OVN setup occurs, the user will see a prompt like:
```
Configure dedicated underlay networking? (yes/no) [default=no]:
```

If `yes`, the users will be asked to select one interface per detected machines (among the remaining interfaces not being used by the previous OVN setup) and will be prompted to enter a ipv4 subnet for the gateway with a ip range. If `no`, the setup is skipped.

## Preseed mode

We'll introduce the following YAML keys:

* `ovn_underlay_interface: <INTERFACE_NAME>` to characterise a node's network interface for the east-west traffic (in the same fashion as `ovn_uplink_interface` for the north-south traffic) 
* And the `ovn_underlay` field to describe the subnet used with the ip range (just like the existing `ovn` field does for the uplink connection)
```yaml
# `ovn_underlay` is optional and represents the private OVN east-west network configuration for LXD.
ovn_underlay:
  ipv4_gateway: 10.0.0.1/24
  ipv4_range: 10.0.0.100-10.0.0.254
  ipv6_gateway: cafe::1/64
```
