### ISSUE TITLE
docs: Is this a typo or? 

### ISSUE THREAD

**Issue by kundeng** [canonical/microcloud#403]
*Please describe the question or issue you're facing with "Get started with MicroCloud".*

```
cat << EOF > /etc/netplan/99-microcloud.yaml
# MicroCloud requires a network interface that doesn't have an IP address
network:
    version: 2
    ethernets:
        enp6s0:
            accept-ra: false
            dhcp4: false
            link-local: []
EOF
chmod 0600 /etc/netplan/99-microcloud.yaml
```

Later in the document, it says enp5s0

---
*Reported from: https://canonical-microcloud.readthedocs-hosted.com/en/latest/microcloud/tutorial/get_started/*
